### ISSUE TITLE
Strings as keys in IDL maps

### ISSUE THREAD

**Issue by pbustos** [eProsima/Fast-RTPS-Gen#23]
After the modification fastrtpsgen kindly offered in
https://github.com/eProsima/Fast-RTPS-Gen/tree/feature/complex_key_map  
we have found:
- one line is missing in grade.build to generate the "share" folder: 
destinationDir = file(new File(projectDir, 'share/fastrtpsgen/java'))
- in the new code in "else" remained  preventing the execution of the new functionality.
- although after changing that the same error persists:

scripts/fastrtpsgen prueba.idl  -replace
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
Loading templates...
Processing the file prueba.idl...
ERROR: Class com.eprosima.idl.parser.typecode.StringTypeCode has no such attribute: size in template context [struct_type if(ctx.anyCdr)_subtemplate anonymous if(!member.annotationNonSerialized)_subtemplate max_serialized_size elseif(typecode.isMapType)_subtemplate map_max_serialized_size]
java.lang.NoSuchFieldException: size
  at java.base/java.lang.Class.getField(Class.java:1999)
  at org.antlr.stringtemplate.language.ASTExpr.rawGetObjectProperty(ASTExpr.java:524)
  at org.antlr.stringtemplate.language.ASTExpr.getObjectProperty(ASTExpr.java:416)
  at org.antlr.stringtemplate.language.ActionEvaluator.attribute(ActionEvaluator.java:351)
  at org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:136)
  at org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:84)
  at org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
  at org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
  at org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:722)
  at org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:659)
  at org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
  at org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
  at org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
  at org.antlr.stringtemplate.language.ConditionalExpr.writeSubTemplate(ConditionalExpr.java:152)
  at org.antlr.stringtemplate.language.ConditionalExpr.write(ConditionalExpr.java:113)
  at org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
  at org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:722)
  at org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:659)
  at org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
  at org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
  at org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
  at org.antlr.stringtemplate.language.ConditionalExpr.writeSubTemplate(ConditionalExpr.java:152)
  at org.antlr.stringtemplate.language.ConditionalExpr.write(ConditionalExpr.java:103)
  at org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
  at org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:722)
  at org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:742)
  at org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:659)
  at org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
  at org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
  at org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
  at org.antlr.stringtemplate.language.ConditionalExpr.writeSubTemplate(ConditionalExpr.java:152)
  at org.antlr.stringtemplate.language.ConditionalExpr.write(ConditionalExpr.java:103)
  at org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
  at org.antlr.stringtemplate.StringTemplate.toString(StringTemplate.java:1635)
  at org.antlr.stringtemplate.StringTemplate.toString(StringTemplate.java:1626)
  at com.eprosima.idl.generator.manager.TemplateGroup.setAttribute(TemplateGroup.java:90)
  at com.eprosima.idl.parser.grammar.IDLParser.specification(IDLParser.java:331)
  at com.eprosima.fastrtps.fastrtpsgen.parseIDL(fastrtpsgen.java:602)
  at com.eprosima.fastrtps.fastrtpsgen.process(fastrtpsgen.java:495)
  at com.eprosima.fastrtps.fastrtpsgen.execute(fastrtpsgen.java:334)
  at com.eprosima.fastrtps.fastrtpsgen.main(fastrtpsgen.java:1199)

It looks likes the class StringTypeCode does not implement the function size(), neither the class StructTypeCode implements getSize()

Thanks

**Comment by LuisGP** [comment]
Hi @pbustos 

Thank you very much for opening this PR.
This morning the branch `https://github.com/eProsima/Fast-RTPS-Gen/tree/feature/complex_key_map` was updated. Did you try with the updated version?

**Comment by pbustos** [comment]
Thanks for the quick answer.

We only managed to make it work with at least openjdk version "11.0.6" 2020-01-14.
With the current Ubuntu 18.04 version we still get:

pbustos@robex:~/software/Fast-RTPS-Gen$ scripts/fastrtpsgen caca.idl 
Error: Invalid or corrupt jarfile scripts/../share/fastrtpsgen/java/fastrtpsgen.jar
pbustos@robex:~/software/Fast-RTPS-Gen$ openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

Is this correct?

**Comment by pbustos** [comment]
After updating to openjdk 11.0.6 (also in U18.04) the generator works smoothly.

Thanks again
